version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"            # Pfad zur Dockerfile
    schedule:
      interval: "weekly"       # oder "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
